# Generated by Django 3.2.9 on 2021-11-26 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='measurement-c0ac497e-0e48-42d6-b74d-adc57f15a6db', max_length=50, unique=True)),
                ('notes', models.TextField(blank=True, help_text='description or notes for this measurement', null=True)),
                ('time_measured', models.DateTimeField(help_text='time the data was measured')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='fist time this measurement was saved to database')),
                ('time_changed', models.DateTimeField(auto_now=True, help_text='last time this measurement was changed')),
                ('data', models.TextField(help_text='file data, serialized to string in a suitable way')),
                ('data_handler', models.CharField(choices=[('NumericCsv', 'NumericCsvHandler')], max_length=10)),
            ],
            options={
                'ordering': ['time_created'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('model_type', models.CharField(choices=[('Test', 'TestModelType')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.measurement')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.model')),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portal.source'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='user_changed',
            field=models.ForeignKey(help_text='user that last changed this measurement in the database', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='measurement',
            name='user_created',
            field=models.ForeignKey(help_text='user that created this measurement in the database', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
