# Generated by Django 3.2.9 on 2021-11-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='name',
            field=models.CharField(default='measurement-51757060-c60a-4a8e-9999-6db3cf327e50', max_length=50, unique=True),
        ),
    ]
