# Generated by Django 3.2.9 on 2021-11-14 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_auto_20211114_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='user_changed',
            field=models.ForeignKey(default=None, help_text='user that last changed this measurement in the database', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='user_created',
            field=models.ForeignKey(default=None, help_text='user that created this measurement in the database', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='auth.user'),
            preserve_default=False,
        ),
    ]
