# Generated by Django 3.2.9 on 2021-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_measurement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='model',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='model',
            name='type',
        ),
        migrations.AddField(
            model_name='measurement',
            name='data',
            field=models.TextField(default='{]}', help_text='file data, serialized to string in a suitable way'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='data_handler',
            field=models.CharField(choices=[('NumericCsv', 'TestDataType')], default='NumericCsv', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('Test', 'TestModelType')], default='Test', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(default='measurement-9d41dc4b-e8ae-4ccc-b115-6382af3e9306', max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='MeasurementDataType',
        ),
        migrations.DeleteModel(
            name='ModelType',
        ),
    ]
