# Generated by Django 3.2.9 on 2021-11-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_measurement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
