# Generated by Django 3.2.9 on 2021-11-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20211126_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='data_handler_id',
            field=models.CharField(choices=[('NumericCsv', 'NumericCsvHandler')], max_length=10),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(default='measurement-90ec5380-3874-4729-84ed-acc91265196d', max_length=50, unique=True),
        ),
    ]
