# Generated by Django 3.2.9 on 2021-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20211126_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='data_handler_id',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='data_handler',
            field=models.CharField(choices=[('NumericCsv', 'NumericCsvHandler')], max_length=10),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(default='measurement-d55f8422-aece-4d71-8934-ee64b4c98e0f', max_length=50, unique=True),
        ),
    ]
