# Generated by Django 3.2.9 on 2021-12-05 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0006_alter_prediction_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='time_changed',
            field=models.DateTimeField(auto_now=True, help_text='last time this measurement was changed'),
        ),
        migrations.AddField(
            model_name='model',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='fist time this measurement was saved to database'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='user_changed',
            field=models.ForeignKey(default=1, help_text='user that last changed this model in the database', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='user_created',
            field=models.ForeignKey(default=1, help_text='user that created this model in the database', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='time it was generated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoring',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='time it was generated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('Test', 'TestModelType'), ('LinearRegr', 'Linear regression')], max_length=10),
        ),
    ]
