# Generated by Django 3.2.9 on 2021-12-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20211219_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='measurement',
            name='groups',
            field=models.ManyToManyField(to='portal.Group'),
        ),
    ]
