# Generated by Django 3.2.9 on 2022-01-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20211219_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['time_created']},
        ),
        migrations.AddField(
            model_name='model',
            name='groups',
            field=models.ManyToManyField(to='portal.Group'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='data_handler',
            field=models.CharField(choices=[('NumericCsv', 'NumericCsv')], max_length=10),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('Test', 'TestModelType'), ('LinearRegr', 'Linear regression'), ('Simca', 'SimcaModel')], max_length=10),
        ),
    ]
